#!/bin/sh
# Pre-commit Git hook to run Black formatter and Ruff linting

echo "Running black formatter and ruff linter..."

# Get list of staged Python files
staged_python_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.py$')

if [ -z "$staged_python_files" ]; then
    echo "No Python files to check."
    exit 0
fi

# Run black formatter on staged Python files
echo "Running black formatter..."
black --line-length 199 $staged_python_files
format_exit_code=$?

if [ $format_exit_code -ne 0 ]; then
    echo "Formatting failed! Please fix the issues before committing."
    exit 1
fi

# Run ruff linter on staged Python files
echo "Running ruff linter..."
ruff check --fix $staged_python_files
lint_exit_code=$?

if [ $lint_exit_code -ne 0 ]; then
    echo "Linting failed! Please fix the issues before committing."
    exit 1
fi

echo "Formatting and linting passed."
exit 0